Repository Metatavu/seligson-taskusalkku, pull requests merged in 2022-02, with the labels that each got.

#68 euro sign and decimal separator
  src/components/generic/fund-card.tsx
  src/components/generic/fund-details.tsx
  src/components/generic/portfolio-security-card.tsx
  src/components/generic/transactions-card.tsx
  src/components/screens/portfolio/distributions-screen.tsx
  src/components/screens/portfolio/transaction-details-screen.tsx
  src/types/index.ts
  src/utils/calculations.ts
  src/utils/chart.ts
  src/utils/injectables.ts
Labels: bug

#75 Feature 73 login flow changes
  src/components/generic/radio-button-option-item.tsx
  src/components/screens/auth/keycloak-login-screen.tsx
  src/components/screens/auth/login-required-screen.tsx
  src/components/screens/auth/welcome-screen.tsx
  src/components/screens/authentication-screen.tsx
  src/components/screens/funds/fund-details-screen.tsx
  src/components/screens/home/portfolio-screen.tsx
  src/components/screens/settings-screen.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
  src/root.tsx
  src/styles/screens/auth/login-screen.ts
  src/types/config.ts
Labels: enhancement

#79 distribution screen show risk button
  src/components/screens/portfolio/distributions-screen.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
  src/localization/sv.json
  src/styles/screens/portfolio/distribution-screen.ts
  src/theme/index.ts
  src/theme/types.ts
  src/types/index.ts
  src/utils/generic.ts
Labels: enhancement

#77 Fixed application language change
  src/components/screens/auth/keycloak-login-screen.tsx
  src/components/screens/auth/login-required-screen.tsx
  src/components/screens/home-screen.tsx
  src/components/screens/home/portfolio-screen.tsx
  src/components/screens/settings-screen.tsx
  src/features/auth/auth-slice.ts
  src/root.tsx
Labels: bug, enhancement

#86 Fixed bio-metric prompt
  src/components/screens/auth/keycloak-login-screen.tsx
  src/components/screens/auth/login-required-screen.tsx
  src/components/screens/home/portfolio-screen.tsx
  src/features/auth/auth-slice.ts
Labels: bug
