Repository Metatavu/seligson-taskusalkku, pull requests merged in 2022-03, with the labels that each got.

#100 Feature 99 fixes to version 4
  App.tsx
  package-lock.json
  package.json
  src/components/generic/transactions-card.tsx
  src/components/screens/funds/active-funds-screen.tsx
  src/components/screens/funds/combination-funds-screen.tsx
  src/components/screens/funds/interest-funds-screen.tsx
  src/components/screens/funds/passive-funds-screen.tsx
  src/components/screens/portfolio/transaction-details-screen.tsx
  src/components/screens/publications/publications-list-screen.tsx
  src/components/screens/publications/publications-list.tsx
  src/components/screens/settings-screen.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
  src/localization/sv.json
  src/root.tsx
  src/utils/funds.ts
  src/utils/generic.ts
  src/utils/injectables.ts
Labels: bug, enhancement

#103 Added sentry configs
  app.config.ts
  app.json
  index.tsx
  package-lock.json
  package.json
Labels: enhancement

#112 added check for offline token
  src/components/containers/auth-refresh.tsx
Labels: bug

#114 Added fixes for release
  App.tsx
  assets/splash.png
  package-lock.json
  package.json
  src/components/generic/fund-card.tsx
  src/components/providers/portfolio-provider.tsx
  src/components/screens/auth/welcome-screen.tsx
  src/components/screens/funds/subscription-settings-screen.tsx
  src/components/screens/home-screen.tsx
  src/components/screens/meeting/meeting-times-screen.tsx
  src/components/screens/meeting/new-meeting-screen.tsx
  src/components/screens/portfolio/distributions-screen.tsx
  src/components/screens/portfolio/my-securities-screen.tsx
  src/components/screens/portfolio/portfolio-select.tsx
  src/components/screens/portfolio/portfolio-tabs-screen.tsx
  src/components/screens/portfolio/statistics-screen.tsx
  src/components/screens/portfolio/transactions-screen.tsx
  src/components/screens/publications/publications-list-screen.tsx
  src/components/screens/settings-screen.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
  src/localization/sv.json
  src/styles/screens/meeting/meeting-times-screen.ts
  src/styles/screens/meeting/new-meeting-screen.ts
  src/styles/screens/portfolio/portfolio-select.ts
  src/styles/screens/portfolio/statistics-screen.ts
  src/styles/screens/settings-screen.ts
  src/theme/index.ts
  src/theme/types.ts
  src/types/index.ts
  src/types/navigators/meeting.ts
  src/utils/funds.ts
  src/utils/my-securities.ts
Labels: bug, enhancement

#116 Feature 113 fixes to public release
  src/app/hooks.ts
  src/components/providers/portfolio-provider.tsx
  src/components/screens/auth/login-required-screen.tsx
  src/components/screens/portfolio/statistics-screen.tsx
  src/components/screens/settings-screen.tsx
Labels: bug
